image: python

stages:
  - build
  - test
  - stage

build-job:
  stage: build
  script:
    - python3 -V

test-job:
  stage: test
  script:
    - python3 hello.py

deploy-job:
  stage: deploy
  script:
    - echo "finished :D"
